GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/60c6e0a819bce91174b3866b

###
DELETE http://localhost:3001/api/notes/60c734c3caa29824d810e705
###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content":"third note for test",
    "important":true
}

###
PUT http://localhost:3001/api/notes/60c7163d6e5712065446de4e
Content-Type: application/json

{
    "content":"Second note for test",
    "important":true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"lol",
    "important":true
}